In [36]:
import torch

In [37]:
shop_to_cons_hits = torch.zeros(8, 3)

shop_to_cons_hits[0, 0] = 1
shop_to_cons_hits[1, 0] = 1
shop_to_cons_hits[2, 0] = 1

shop_to_cons_hits[2, 1] = 1
shop_to_cons_hits[3, 1] = 1
shop_to_cons_hits[6, 1] = 1
shop_to_cons_hits[7, 1] = 1

shop_to_cons_hits[1, 2] = 1
shop_to_cons_hits[4, 2] = 1

In [38]:
shop_to_cons_hits

tensor([[1., 0., 0.],
        [1., 0., 1.],
        [1., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])

In [39]:
shop_to_cons_hits[:, 0]

tensor([1., 1., 1., 0., 0., 0., 0., 0.])

In [44]:
k_corr = 1

acc_at_k_arr = torch.any(shop_to_cons_hits[:k_corr, :] == 1, dim=0)

In [45]:
acc_at_k_arr

tensor([ True, False, False])

In [23]:
shop_to_cons_hits_cumsum = torch.cumsum(shop_to_cons_hits, dim=0)

In [24]:
shop_to_cons_hits_cumsum

tensor([[1., 0., 0.],
        [2., 0., 1.],
        [3., 1., 1.],
        [3., 2., 1.],
        [3., 2., 2.],
        [3., 2., 2.],
        [3., 3., 2.],
        [3., 4., 2.]])

In [27]:
shop_to_cons_hits_cumsum[:, 0]

tensor([1., 2., 3., 3., 3., 3., 3., 3.])

In [25]:
num_chunk_cons_imgs = 3
num_shop_imgs = 8
device = "cpu"

shop_to_cons_arange = torch.stack([torch.arange(num_shop_imgs, device=device) for _ in range(num_chunk_cons_imgs)], dim=1) + 1

In [26]:
shop_to_cons_arange

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [4, 4, 4],
        [5, 5, 5],
        [6, 6, 6],
        [7, 7, 7],
        [8, 8, 8]])

In [28]:
shop_to_cons_arange[:, 0]

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
cons_shop_item_id_counts_chunk = shop_to_cons_hits.sum(dim=0)

In [30]:
cons_shop_item_id_counts_chunk

tensor([3., 4., 2.])

In [33]:
avg_prec_arr_temp_1 = shop_to_cons_hits * shop_to_cons_hits_cumsum / shop_to_cons_arange
avg_prec_arr = torch.sum(avg_prec_arr_temp_1, dim=0) / cons_shop_item_id_counts_chunk

In [34]:
avg_prec_arr_temp_1

tensor([[1.0000, 0.0000, 0.0000],
        [1.0000, 0.0000, 0.5000],
        [1.0000, 0.3333, 0.0000],
        [0.0000, 0.5000, 0.0000],
        [0.0000, 0.0000, 0.4000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.4286, 0.0000],
        [0.0000, 0.5000, 0.0000]])

In [35]:
avg_prec_arr

tensor([1.0000, 0.4405, 0.4500])

In [13]:
arange_arr[:, 0]

tensor([0, 1, 2, 3, 4])