In [101]:
tensor = torch.Tensor([
    [1, 2, 3, 4, 5],
    [1, 3, 5, 7, 9],
    [1, 4, 7, 10, 13],
    [1, 5, 9, 13, 17],
    [1, 6, 11, 16, 21]
])

tensor = tensor[None, None, :]

In [102]:
tensor.shape

torch.Size([1, 1, 5, 5])

In [103]:
tensor

tensor([[[[ 1.,  2.,  3.,  4.,  5.],
          [ 1.,  3.,  5.,  7.,  9.],
          [ 1.,  4.,  7., 10., 13.],
          [ 1.,  5.,  9., 13., 17.],
          [ 1.,  6., 11., 16., 21.]]]])

In [104]:
tensor = tensor.repeat(1, 3, 1, 1)

In [105]:
tensor.shape

torch.Size([1, 3, 5, 5])

In [107]:
convolution = torch.nn.Conv2d(3, 3, 5)

In [108]:
convolution.weight.shape

torch.Size([3, 3, 5, 5])

In [91]:
convolution.bias.shape

torch.Size([5])

In [92]:
convolution.weight.requires_grad = False
convolution.bias.requires_grad = False

In [95]:
convolution.weight[:] = 1
convolution.bias[:] = 0

In [97]:
convolution.bias

Parameter containing:
tensor([0., 0., 0., 0., 0.])

In [98]:
tensor_new = convolution(tensor)

In [99]:
tensor_new.shape

torch.Size([1, 5, 1, 1])

In [100]:
tensor_new

tensor([[[[875.]],

         [[875.]],

         [[875.]],

         [[875.]],

         [[875.]]]])