In [73]:
import os
import shutil
import sys
import pathlib
import pickle as pkl
import json
import argparse

import numpy as np
import pandas as pd

import torch
import torchvision

from torch.utils.data import DataLoader, Subset

from datasets import deep_fashion_ctsrbm
from arch import backbones, models, heads

from tqdm import tqdm

import utils.mem
import utils.list
import utils.train
import utils.time
import utils.log
import utils.dict
import utils.sig
import utils.pkl
import utils.chunk
import utils.arr
import utils.ten

from time import time
from datetime import datetime

from itertools import chain
from functools import reduce

import json
import socket

import pprint



def print_tensor_info(tensor, name, logger):

    logger.print(
        "{:s}:".format(name),
        tensor.shape,
        tensor.dtype,
        tensor.device,
        utils.mem.sprint_fancy_num_bytes(utils.mem.get_num_bytes(tensor))
    )



########
# COMPONENT FUNCTIONS
########



def create_backbone(backbone_class):

    if backbone_class == "ResNet50Backbone":
        backbone = backbones.ResNet50Backbone()
    if backbone_class == "EfficientNetB3Backbone":
        backbone = backbones.EfficientNetB3Backbone()
    if backbone_class == "EfficientNetB4Backbone":
        backbone = backbones.EfficientNetB4Backbone()
    if backbone_class == "EfficientNetB5Backbone":
        backbone = backbones.EfficientNetB5Backbone()
    if backbone_class == "ConvNeXtTinyBackbone":
        backbone = backbones.ConvNeXtTinyBackbone(contiguous_after_permute=True)

    return backbone


def load_experiment_checkpoint(
        experiment_checkpoint_filename,
        exp_params,
        device
        ):

    # Load checkpoint

    experiment_checkpoint = torch.load(experiment_checkpoint_filename)

    # Backbone

    backbone_class = exp_params["settings"]["backbone"]["class"]

    backbone = create_backbone(backbone_class).to(device)

    backbone.load_state_dict(experiment_checkpoint["backbone_state_dict"])

    # Head

    ret_head = heads.RetHead(backbone.out_shape, 1024).to(device)

    ret_head.load_state_dict(experiment_checkpoint["ret_head_state_dict"])

    return (backbone, ret_head)



########
# DATASET FUNCTIONS
########



def create_backbone_transform(backbone_class):

    if backbone_class == "ResNet50Backbone":
        backbone_image_transform = torchvision.models.ResNet50_Weights.DEFAULT.transforms()
    if backbone_class == "EfficientNetB3Backbone":
        backbone_image_transform = torchvision.models.EfficientNet_B3_Weights.DEFAULT.transforms()
    if backbone_class == "EfficientNetB4Backbone":
        backbone_image_transform = torchvision.models.EfficientNet_B4_Weights.DEFAULT.transforms()
    if backbone_class == "EfficientNetB5Backbone":
        backbone_image_transform = torchvision.models.EfficientNet_B5_Weights.DEFAULT.transforms()
    if backbone_class == "ConvNeXtTinyBackbone":
        backbone_image_transform = torchvision.models.ConvNeXt_Tiny_Weights.DEFAULT.transforms()

    return backbone_image_transform



########
# JSON DATA FUNCTIONS
########



def save_json_data(
        json_data_filename,
        json_data
        ):

    with open(json_data_filename, 'w') as json_data_file:
        json.dump(json_data, json_data_file, indent=2)


def load_json_data(
        json_data_filename
        ):

    with open(json_data_filename, 'r') as json_data_file:
        json_data = json.load(json_data_file)

    return json_data



########
# PERFORMANCE FUNCTIONS
########



def compute_embeddings_and_item_ids(
    ret_model,
    image_loader,
    device,
    with_tqdm
):

    ret_model.eval()

    # Embedding calculation

    all_img_embs = torch.tensor([], dtype=float).to(device)
    all_item_ids = torch.tensor([], dtype=int).to(device)

    loader_gen = image_loader
    if with_tqdm: loader_gen = tqdm(loader_gen)

    with torch.no_grad():

        for batch in loader_gen:

            # img_embs

            imgs = batch[0].to(device)
            img_embs = ret_model(imgs)
            all_img_embs = torch.cat([all_img_embs, img_embs])

            # item_ids

            item_ids = batch[1].to(device)
            all_item_ids = torch.cat([all_item_ids, item_ids])

    return all_img_embs, all_item_ids

In [2]:
def compute_performance_metrics(
    shop_img_embs,
    shop_item_ids,
    cons_img_embs,
    cons_item_ids,
    k_values,
    cons_imgs_chunk_size,
    with_tqdm
):

    num_cons_imgs = cons_img_embs.shape[0]

    avg_p_at_k_dict = {k: 0 for k in k_values}
    avg_r_at_k_dict = {k: 0 for k in k_values}

    # Precision and recall metrics

    ## [i]: Number of shop items with the same item id as cons img i

    cons_shop_item_id_counts = torch.empty_like(cons_item_ids)

    for idx, cons_item_id in enumerate(cons_item_ids):
        counts = torch.sum(torch.eq(shop_item_ids, cons_item_id))
        cons_shop_item_id_counts[idx] = counts

    cons_img_idxs_chunk_gen = utils.chunk.chunk_partition_size(np.arange(num_cons_imgs), cons_imgs_chunk_size)
    if with_tqdm: cons_img_idxs_chunk_gen = tqdm(cons_img_idxs_chunk_gen)

    for cons_img_idxs_chunk in cons_img_idxs_chunk_gen:

        ## [i, j]: Distance from shop img i to cons img j

        shop_to_cons_dists = torch.cdist(shop_img_embs, cons_img_embs[cons_img_idxs_chunk, :])

        ## [:, i]: Ordered closest shop img idxs to cons img i

        shop_to_cons_ordered_idxs = torch.argsort(shop_to_cons_dists, dim=0)

        ## [:, i]: ordered closest shop img item ids to cons img i 

        shop_to_cons_nearest_item_ids = shop_item_ids[shop_to_cons_ordered_idxs]

        ## [:, i]: True/False if, for each shop image, the cons img i is of the same item id

        shop_to_cons_hits = torch.eq(shop_to_cons_nearest_item_ids, cons_item_ids[cons_img_idxs_chunk])

        for k in k_values:

            k_corr = shop_img_embs.shape[0] if k == -1 else k

            ## [i]: Number of hits of cons img i (out of the k first)

            shop_to_cons_hits_sum = torch.sum(shop_to_cons_hits[:k_corr, ], dim=0)

            ## [i]: p/r_at_k of cons img i

            p_at_k = shop_to_cons_hits_sum / k_corr
            r_at_k = shop_to_cons_hits_sum / cons_shop_item_id_counts[cons_img_idxs_chunk]

            ## Accumulate results

            avg_p_at_k_dict[k] += torch.sum(p_at_k).item()
            avg_r_at_k_dict[k] += torch.sum(r_at_k).item()

    ## Average results
    
    for k in k_values:

        avg_p_at_k_dict[k] /= num_cons_imgs
        avg_r_at_k_dict[k] /= num_cons_imgs

    # Composite metrics

    avg_f1_at_k_dict = {k: 2 / ((1 / avg_p_at_k_dict[k]) + (1 / avg_r_at_k_dict[k])) for k in k_values}

    return avg_p_at_k_dict, avg_r_at_k_dict, avg_f1_at_k_dict

In [3]:
def compute_closest_idxs(
    shop_img_embs,
    shop_img_idxs,
    shop_item_ids,
    cons_img_embs,
    cons_img_idxs,
    cons_item_ids,
    desired_cons_img_idxs,
    num_desired_shop_imgs,
    cons_imgs_chunk_size,
    with_tqdm,
    device
):
    """
    """

    shop_img_idxs = torch.tensor(shop_img_idxs).to(device)
    shop_item_ids = shop_item_ids.to(device)
    
    # Result tensors

    num_desired_cons_imgs = len(desired_cons_img_idxs)

    ## [i, j]: j-th closest shop img idx to cons img with desired zidx i
    ## [i, j]: j-th closest shop item id to cons img with desired zidx i
    ## [i, j]: j-th closest shop dist to cons img with desired zidx i

    shop_to_desired_cons_ordered_closest_img_idxs = torch.empty(size=(num_desired_cons_imgs, num_desired_shop_imgs), dtype=int).to(device)
    shop_to_desired_cons_ordered_closest_item_ids = torch.empty(size=(num_desired_cons_imgs, num_desired_shop_imgs), dtype=int).to(device)
    shop_to_desired_cons_ordered_closest_dists = torch.empty(size=(num_desired_cons_imgs, num_desired_shop_imgs), dtype=float).to(device)
    
    # Counts of correct shop images

    ## [i]: Number of shop items with the same item id as cons img i

    cons_shop_item_id_counts = torch.empty_like(cons_item_ids)

    for idx, cons_item_id in enumerate(cons_item_ids):
        counts = torch.sum(torch.eq(shop_item_ids, cons_item_id))
        cons_shop_item_id_counts[idx] = counts

    # Preparing desired_cons_img_zidxs chunks

    desired_cons_img_zidxs = utils.arr.compute_zidxs(cons_img_idxs, desired_cons_img_idxs)
    desired_cons_img_zzidxs = np.arange(num_desired_cons_imgs)
    
    desired_cons_img_zidxs_chunk_gen = utils.chunk.chunk_partition_size(desired_cons_img_zidxs, cons_imgs_chunk_size)
    desired_cons_img_zzidxs_chunk_gen = utils.chunk.chunk_partition_size(desired_cons_img_zzidxs, cons_imgs_chunk_size)    
    
    chunk_idxs_gen = zip(desired_cons_img_zidxs_chunk_gen, desired_cons_img_zzidxs_chunk_gen)
    if with_tqdm: chunk_idxs_gen = tqdm(chunk_idxs_gen)

    for desired_cons_img_zidxs_chunk, desired_cons_img_zzidxs_chunk in chunk_idxs_gen:

        ## [j, i]: Distance from shop img zidx j to cons img with zidx i

        shop_to_cons_dists = torch.cdist(shop_img_embs, cons_img_embs[desired_cons_img_zidxs_chunk, :])

        ## [:, i]: Ordered closest shop img zidxs to cons img with zidx i

        shop_to_cons_ordered_closest_zidxs = torch.argsort(shop_to_cons_dists, dim=0).to(device)

        ## [:, i]: Ordered closest shop img idxs to cons img with zidx i 
        ## [:, i]: Ordered closest shop item ids to cons img with zidx i 
        ## [:, i]: Ordered closest shop img distances to cons img with zidx i 

        shop_to_cons_ordered_closest_img_idxs = shop_img_idxs[shop_to_cons_ordered_closest_zidxs]
        shop_to_cons_ordered_closest_item_ids = shop_item_ids[shop_to_cons_ordered_closest_zidxs]
        shop_to_cons_ordered_closest_dists = torch.take_along_dim(shop_to_cons_dists, shop_to_cons_ordered_closest_zidxs, dim=0)

        shop_to_desired_cons_ordered_closest_img_idxs[desired_cons_img_zzidxs_chunk, :] = torch.t(shop_to_cons_ordered_closest_img_idxs[:num_desired_shop_imgs, :])
        shop_to_desired_cons_ordered_closest_item_ids[desired_cons_img_zzidxs_chunk, :] = torch.t(shop_to_cons_ordered_closest_item_ids[:num_desired_shop_imgs, :])
        shop_to_desired_cons_ordered_closest_dists[desired_cons_img_zzidxs_chunk, :] = torch.t(shop_to_cons_ordered_closest_dists[:num_desired_shop_imgs, :])

    # Indexing counts

    cons_shop_item_id_counts = cons_shop_item_id_counts[desired_cons_img_zzidxs]

    return (
        shop_to_desired_cons_ordered_closest_img_idxs,
        shop_to_desired_cons_ordered_closest_item_ids,
        shop_to_desired_cons_ordered_closest_dists,
        cons_shop_item_id_counts
    )

---

In [4]:
torch.autograd.set_detect_anomaly(True)

datetime_now_str = datetime.now().strftime("%d-%m-%Y--%H:%M:%S")


####
# COMMAND ARGUMENTS
####


parser = argparse.ArgumentParser()
parser.add_argument("eval_params_filename", help="filename of the evaluation params json file inside the \"eval_params\" directory")
parser.add_argument("exp_params_filename", help="filename of the experiment params json file inside the \"exp_params\" directory")
parser.add_argument("--silent", help="no terminal prints will be made", action="store_true")
parser.add_argument("--notqdm", help="no tqdm bars will be shown", action="store_true")

command = "python eval_ctsrbm_examples.py resnet_ret_train/test_50_000__eval_ctsrbm_examples.json resnet_ret_train/test_50_000__train_ret_DDP.json"
command_args = parser.parse_args(command.split()[2:])

eval_params_filename = os.path.join(pathlib.Path.home(), "fashion_retrieval", "exp_params", command_args.eval_params_filename)
exp_params_filename = os.path.join(pathlib.Path.home(), "fashion_retrieval", "exp_params", command_args.exp_params_filename)

with_tqdm = not command_args.notqdm and not command_args.silent

####
# EVALUATION PREREQUISITES
####


# Read params

eval_params = load_json_data(eval_params_filename)
exp_params = load_json_data(exp_params_filename)

# Experiment directory

experiment_name__eval = eval_params["experiment_name"]
experiment_name__exp = exp_params["experiment_name"]

if experiment_name__eval != experiment_name__exp:
    raise ValueError("Experiment names do not match")


####
# PREPARE LOGGER
####


experiment_name = eval_params["experiment_name"]
experiment_dirname = os.path.join(pathlib.Path.home(), "data", "fashion_retrieval", experiment_name)

log_filename = "eval_ctsrbm_examples_logs.txt"
log_full_filename = os.path.join(experiment_dirname, log_filename)
if os.path.exists(log_full_filename):
    os.remove(log_full_filename)

logger_streams = [log_full_filename]
if not command_args.silent: logger_streams.append(sys.stdout)

logger = utils.log.Logger(logger_streams)

logger.print("Command arguments:", " ".join(sys.argv))


####
# PREPARE EVAL DATA
####


eval_data = {}

eval_data["script_name"] = "eval_ctsrbm_examples.py"
eval_data["command_args"] = sys.argv
eval_data["experiment_name"] = eval_params["experiment_name"]
eval_data["settings"] = {}
eval_data["results"] = {}

eval_data["settings"]["datasets"] = [
    "DeepFashion Consumer-to-shop Clothes Retrieval Benchmark"
]

eval_data["settings"]["model_checkpoint"] = eval_params["settings"]["model_checkpoint"]


####
# GPU INITIALIZATION
####


logger.print("Selecting CUDA devices")

os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"

device_idx = eval_params["settings"]["device_idx"]
os.environ["CUDA_VISIBLE_DEVICES"] = ",".join([str(idx) for idx in [device_idx]])

device = torch.device(0)

torch.cuda.empty_cache()

eval_data["settings"]["gpu_usage"] = utils.mem.list_gpu_data([device_idx])
eval_data["settings"]["hostname"] = socket.gethostname()

logger.print("Selected CUDA devices")

logger.print("Current memory usage:")
logger.print(utils.mem.sprint_memory_usage([eval_params["settings"]["device_idx"]], num_spaces=2))


####
# DATA INITIALIZATION
####


logger.print("Initializing image loader dataset")

# Dataset initialization

backbone_class = exp_params["settings"]["backbone"]["class"]

backbone_image_transform = create_backbone_transform(backbone_class)
backbone_image_transform.antialias = True

ctsrbm_dataset_dir = os.path.join(pathlib.Path.home(), "data", "DeepFashion", "Consumer-to-shop Clothes Retrieval Benchmark")

ctsrbm_dataset = deep_fashion_ctsrbm.ConsToShopClothRetrBmkImageLoader(ctsrbm_dataset_dir, img_transform=backbone_image_transform)

logger.print("Initialized image loader dataset")


####
# MODEL INITIALIZATION
####


logger.print("Loading model from checkpoint")

# Load components

experiment_checkpoint_filename = eval_params["settings"]["model_checkpoint"]

experiment_checkpoint_filename_full = os.path.join(
    experiment_dirname, experiment_checkpoint_filename
)

backbone, ret_head =\
load_experiment_checkpoint(
    experiment_checkpoint_filename_full,
    exp_params,
    device
)

logger.print("Loaded model from checkpoint")


# Build models

ret_model = models.BackboneAndHead(backbone, ret_head).to(device)

logger.print("Loaded model from checkpoint")


####
# TRAIN PERFORMANCE METRICS
####


logger.print("Train split examples begin")

# Data loader initialization

train_shop_img_idxs = ctsrbm_dataset.get_subset_indices(split="train", domain="shop")
train_cons_img_idxs = ctsrbm_dataset.get_subset_indices(split="train", domain="consumer")

train_shop_dataset = Subset(ctsrbm_dataset, train_shop_img_idxs)
train_cons_dataset = Subset(ctsrbm_dataset, train_cons_img_idxs)

batch_size = eval_params["settings"]["data_loading"]["batch_size"]
num_workers = eval_params["settings"]["data_loading"]["num_workers"]

train_shop_loader = DataLoader(
    train_shop_dataset,
    batch_size=batch_size,
    num_workers=num_workers,
    pin_memory=True,
    shuffle=False
)

train_cons_loader = DataLoader(
    train_cons_dataset,
    batch_size=batch_size,
    num_workers=num_workers,
    pin_memory=True,
    shuffle=False
)

Command arguments: /home-net/gortega/fashion_retrieval/.venv/lib/python3.8/site-packages/ipykernel_launcher.py --ip=127.0.0.1 --stdin=9014 --control=9012 --hb=9011 --Session.signature_scheme="hmac-sha256" --Session.key=b"6ab54d6b-2a3e-4091-a67b-2f967de07c73" --shell=9013 --transport="tcp" --iopub=9015 --f=/home-net/gortega/.local/share/jupyter/runtime/kernel-v2-3309626jeQtbskLb910.json
Selecting CUDA devices
Selected CUDA devices
Current memory usage:
  Device ID  0:  95.875 MiB /  11.000 GiB (  0.85%) - NVIDIA GeForce GTX 1080 Ti
Initializing image loader dataset
Initialized image loader dataset
Loading model from checkpoint
Loaded model from checkpoint
Loaded model from checkpoint
Train split examples begin


In [5]:
# Embedding calculation

logger.print("  Computing image embeddings")

train_shop_img_embs, train_shop_item_ids = compute_embeddings_and_item_ids(
    ret_model,
    train_shop_loader,
    device,
    with_tqdm
    
)

train_cons_img_embs, train_cons_item_ids = compute_embeddings_and_item_ids(
    ret_model,
    train_cons_loader,
    device,
    with_tqdm
)

logger.print("  Computed image embeddings")

  Computing image embeddings


100%|██████████| 3069/3069 [03:07<00:00, 16.36it/s]

  Computed image embeddings


---

In [79]:
# Example calculation

train_desired_cons_img_idxs = eval_params["settings"]["train"]["desired_cons_img_idxs"]
train_num_desired_shop_imgs = eval_params["settings"]["train"]["num_desired_shop_imgs"]
cons_imgs_chunk_size = utils.dict.chain_get(
    eval_params,
    "settings", "cons_imgs_chunk_size",
    default=1000
)

In [80]:
train_desired_cons_img_idxs

[502, 1097, 1502, 2029, 2976]

In [81]:
train_num_desired_shop_imgs

10

In [82]:
(
    shop_img_embs,
    shop_img_idxs,
    shop_item_ids,
    cons_img_embs,
    cons_img_idxs,
    cons_item_ids,
    desired_cons_img_idxs,
    num_desired_shop_imgs,
    cons_imgs_chunk_size,
    with_tqdm,
    device
) = (
    train_shop_img_embs,
    train_shop_img_idxs,
    train_shop_item_ids,
    train_cons_img_embs,
    train_cons_img_idxs,
    train_cons_item_ids,
    train_desired_cons_img_idxs,
    train_num_desired_shop_imgs,
    cons_imgs_chunk_size,
    with_tqdm,
    device
)

In [83]:
shop_img_idxs[:30]

array([  3,  12,  13,  14,  16,  30,  31,  36,  38,  40,  42,  64,  67,
        75,  80,  87,  90,  91,  93,  96,  97, 105, 106, 109, 119, 126,
       130, 137, 140, 141])

In [84]:
shop_item_ids[:30]

tensor([24444, 24434, 24434, 24434, 17990, 17669, 17669, 19192, 13695, 29336,
        30193, 16092, 16092, 28284, 11377, 27615, 26989, 26989, 28410, 19550,
        19550, 17648, 17648, 17238, 30464, 27322, 18358, 12862, 13744, 13744],
       device='cuda:0')

In [85]:
for shop_img_idx, shop_item_id in zip(shop_img_idxs[:30], shop_item_ids[:30]):
    print(shop_img_idx.item(), shop_item_id.item())

3 24444
12 24434
13 24434
14 24434
16 17990
30 17669
31 17669
36 19192
38 13695
40 29336
42 30193
64 16092
67 16092
75 28284
80 11377
87 27615
90 26989
91 26989
93 28410
96 19550
97 19550
105 17648
106 17648
109 17238
119 30464
126 27322
130 18358
137 12862
140 13744
141 13744


In [86]:
shop_img_idxs = torch.tensor(shop_img_idxs).to(device)
shop_item_ids = shop_item_ids.to(device)

# Result tensors

num_desired_cons_imgs = len(desired_cons_img_idxs)

## [i, j]: j-th closest shop img idx to cons img with desired zidx i
## [i, j]: j-th closest shop item id to cons img with desired zidx i
## [i, j]: j-th closest shop dist to cons img with desired zidx i

shop_to_desired_cons_ordered_closest_img_idxs = torch.empty(size=(num_desired_cons_imgs, num_desired_shop_imgs), dtype=int).to(device)
shop_to_desired_cons_ordered_closest_item_ids = torch.empty(size=(num_desired_cons_imgs, num_desired_shop_imgs), dtype=int).to(device)
shop_to_desired_cons_ordered_closest_dists = torch.empty(size=(num_desired_cons_imgs, num_desired_shop_imgs), dtype=float).to(device)

# Counts of correct shop images

## [i]: Number of shop items with the same item id as cons img with zidx i

cons_shop_item_id_counts = torch.empty_like(cons_item_ids)

for cons_img_zidx, cons_item_id in enumerate(cons_item_ids):
    counts = torch.sum(torch.eq(shop_item_ids, cons_item_id))
    cons_shop_item_id_counts[cons_img_zidx] = counts

In [87]:
cons_img_idxs[:30]

array([ 0,  1,  2,  8,  9, 10, 11, 15, 25, 26, 27, 28, 29, 32, 33, 34, 35,
       37, 39, 41, 55, 56, 57, 58, 59, 60, 61, 62, 63, 65])

In [88]:
cons_item_ids[:30]

tensor([24444, 24444, 24444, 24434, 24434, 24434, 24434, 17990, 17669, 17669,
        17669, 17669, 17669, 17669, 19192, 19192, 19192, 13695, 29336, 30193,
        16092, 16092, 16092, 16092, 16092, 16092, 16092, 16092, 16092, 16092],
       device='cuda:0')

In [89]:
for cons_img_idx, cons_item_id in zip(cons_img_idxs[:30], cons_item_ids[:30]):
    print(cons_img_idx.item(), cons_item_id.item())

0 24444
1 24444
2 24444
8 24434
9 24434
10 24434
11 24434
15 17990
25 17669
26 17669
27 17669
28 17669
29 17669
32 17669
33 19192
34 19192
35 19192
37 13695
39 29336
41 30193
55 16092
56 16092
57 16092
58 16092
59 16092
60 16092
61 16092
62 16092
63 16092
65 16092


In [90]:
cons_shop_item_id_counts[:30]

tensor([1, 1, 1, 3, 3, 3, 3, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2], device='cuda:0')

In [91]:
# Preparing desired_cons_img_zidxs chunks

desired_cons_img_zidxs = utils.arr.compute_zidxs(cons_img_idxs, desired_cons_img_idxs)
desired_cons_img_zzidxs = np.arange(num_desired_cons_imgs)

desired_cons_img_zidxs_chunk_gen = utils.chunk.chunk_partition_size(desired_cons_img_zidxs, cons_imgs_chunk_size)
desired_cons_img_zzidxs_chunk_gen = utils.chunk.chunk_partition_size(desired_cons_img_zzidxs, cons_imgs_chunk_size)    

chunk_idxs_gen = zip(desired_cons_img_zidxs_chunk_gen, desired_cons_img_zzidxs_chunk_gen)
#if with_tqdm: chunk_idxs_gen = tqdm(chunk_idxs_gen)
desired_cons_img_zidxs_chunk, desired_cons_img_zzidxs_chunk = next(chunk_idxs_gen)

In [92]:
desired_cons_img_zidxs_chunk

array([186, 356, 498, 664, 971])

In [93]:
desired_cons_img_zzidxs_chunk

array([0, 1, 2, 3, 4])

In [94]:
desired_cons_img_idxs

[502, 1097, 1502, 2029, 2976]

In [95]:
cons_img_idxs[desired_cons_img_zidxs_chunk]

array([ 502, 1097, 1502, 2029, 2976])

In [96]:
cons_item_ids[desired_cons_img_zidxs_chunk]

tensor([22872, 16232, 14698, 27694, 27523], device='cuda:0')

In [97]:
## [j, i]: Distance from shop img zidx j to cons img with zidx i

shop_to_cons_dists = torch.cdist(shop_img_embs, cons_img_embs[desired_cons_img_zidxs_chunk, :])

## [:, i]: Ordered closest shop img zidxs to cons img with zidx i

shop_to_cons_ordered_closest_zidxs = torch.argsort(shop_to_cons_dists, dim=0).to(device)

In [98]:
utils.ten.print_tensor_info(shop_to_cons_dists, "shop_to_cons_dists")

name: shop_to_cons_dists
  shape:  torch.Size([22723, 5])
  dtype:  torch.float64
  device:  cuda:0
  mem:  887.688 KiB


In [99]:
shop_to_cons_dists[:, 0]

tensor([6.3674, 6.8429, 5.9824,  ..., 8.7328, 6.3396, 6.3854], device='cuda:0',
       dtype=torch.float64)

In [100]:
shop_to_cons_dists[0, :]

tensor([6.3674, 6.9056, 8.2916, 8.2196, 7.4310], device='cuda:0',
       dtype=torch.float64)

In [101]:
utils.ten.print_tensor_info(shop_to_cons_ordered_closest_zidxs, "shop_to_cons_ordered_closest_zidxs")

name: shop_to_cons_ordered_closest_zidxs
  shape:  torch.Size([22723, 5])
  dtype:  torch.int64
  device:  cuda:0
  mem:  887.688 KiB


In [102]:
shop_to_cons_ordered_closest_zidxs[:, 0]

tensor([  264,   142, 10278,  ..., 17542, 17909,  2787], device='cuda:0')

In [103]:
shop_to_cons_ordered_closest_zidxs[0, :]

tensor([  264, 10705,   178, 16297, 14571], device='cuda:0')

In [104]:
my_ten = shop_to_cons_dists[:, 0][shop_to_cons_ordered_closest_zidxs[:, 0]]

In [105]:
utils.ten.print_tensor_info(my_ten, "my_ten")

name: my_ten
  shape:  torch.Size([22723])
  dtype:  torch.float64
  device:  cuda:0
  mem:  177.594 KiB


In [106]:
my_ten[:10]

tensor([4.6781, 4.7327, 4.8759, 4.8931, 4.9059, 4.9107, 4.9230, 4.9456, 4.9699,
        4.9800], device='cuda:0', dtype=torch.float64)

In [107]:
## [:, i]: Ordered closest shop img idxs to cons img with zidx i 
## [:, i]: Ordered closest shop item ids to cons img with zidx i 
## [:, i]: Ordered closest shop img distances to cons img with zidx i 

shop_to_cons_ordered_closest_img_idxs = shop_img_idxs[shop_to_cons_ordered_closest_zidxs]
shop_to_cons_ordered_closest_item_ids = shop_item_ids[shop_to_cons_ordered_closest_zidxs]
shop_to_cons_ordered_closest_dists = torch.take_along_dim(shop_to_cons_dists, shop_to_cons_ordered_closest_zidxs, dim=0)

# Repeated comments
## [i, j]: j-th closest shop img idx to cons img with desired zidx i
## [i, j]: j-th closest shop item id to cons img with desired zidx i
## [i, j]: j-th closest shop dist to cons img with desired zidx i

shop_to_desired_cons_ordered_closest_img_idxs[desired_cons_img_zzidxs_chunk, :] = torch.t(shop_to_cons_ordered_closest_img_idxs[:num_desired_shop_imgs, :])
shop_to_desired_cons_ordered_closest_item_ids[desired_cons_img_zzidxs_chunk, :] = torch.t(shop_to_cons_ordered_closest_item_ids[:num_desired_shop_imgs, :])
shop_to_desired_cons_ordered_closest_dists[desired_cons_img_zzidxs_chunk, :] = torch.t(shop_to_cons_ordered_closest_dists[:num_desired_shop_imgs, :])

In [108]:
shop_to_cons_ordered_closest_img_idxs[:num_desired_shop_imgs, 0]

tensor([  2133,   1216, 106622, 186259, 124060, 156906,   1360,  98885,  93252,
          3491], device='cuda:0')

In [109]:
shop_to_cons_ordered_closest_item_ids[:num_desired_shop_imgs, 0]

tensor([ 9151, 24290, 11877,  7704, 10576, 10718, 13258, 21744, 26467, 20749],
       device='cuda:0')

In [111]:
cons_shop_item_id_counts_orig = cons_shop_item_id_counts.clone()

In [112]:
utils.ten.print_tensor_info(cons_shop_item_id_counts_orig, "cons_shop_item_id_counts_orig")

name: cons_shop_item_id_counts_orig
  shape:  torch.Size([98204])
  dtype:  torch.int64
  device:  cuda:0
  mem:  767.289 KiB


In [113]:
desired_cons_img_zidxs

array([186, 356, 498, 664, 971])

In [114]:
desired_cons_img_zzidxs

array([0, 1, 2, 3, 4])

In [115]:
# Indexing counts

cons_shop_item_id_counts = cons_shop_item_id_counts[desired_cons_img_zidxs]

In [35]:
cons_shop_item_id_counts[0]

tensor(1, device='cuda:0')

---

In [ ]:
# Save evaluation data

eval_data["results"]["train"] = []

train_desired_cons_img_zidxs = utils.arr.compute_zidxs(train_cons_img_idxs, train_desired_cons_img_idxs)

In [45]:
train_desired_cons_img_zidxs

array([186, 356, 498, 664, 971])

In [46]:
train_desired_cons_img_idxs

[502, 1097, 1502, 2029, 2976]

In [58]:
train_cons_img_idxs[train_desired_cons_img_zidxs]

array([ 502, 1097, 1502, 2029, 2976])

In [57]:
idx_a, idx_b = 175, 200

for train_cons_img_idx, train_cons_item_id in zip(train_cons_img_idxs[idx_a:idx_b], train_cons_item_ids[idx_a:idx_b]):
    print(train_cons_img_idx, train_cons_item_id.item())

442 17413
444 11904
446 12964
448 27443
495 22872
496 22872
497 22872
498 22872
499 22872
500 22872
501 22872
502 22872
503 22872
504 22872
506 22872
507 22872
509 22872
510 22872
511 22872
512 30135
513 30135
517 12508
518 12508
519 12508
520 12508


In [59]:
train_desired_cons_img_zidxs[0]

186

In [60]:
cons_img_idx = train_cons_img_idxs[train_desired_cons_img_zidxs[0]]
cons_item_id = train_cons_item_ids[train_desired_cons_img_zidxs[0]]

In [61]:
cons_img_idx, cons_item_id

(502, tensor(22872, device='cuda:0'))

In [77]:
eval_data["results"]["train"] = []

for train_desired_cons_img_zzidx, train_desired_cons_img_zidx in enumerate(train_desired_cons_img_zidxs):

    cons_img_idx = train_cons_img_idxs[train_desired_cons_img_zidx]
    cons_item_id = train_cons_item_ids[train_desired_cons_img_zidx]
    shop_item_id_counts = cons_shop_item_id_counts[train_desired_cons_img_zzidx]
    closest_shop_img_idxs = shop_to_desired_cons_ordered_closest_img_idxs[train_desired_cons_img_zzidx, :]
    closest_shop_item_ids = shop_to_desired_cons_ordered_closest_item_ids[train_desired_cons_img_zzidx, :]
    closest_shop_img_dists = shop_to_desired_cons_ordered_closest_dists[train_desired_cons_img_zzidx, :]

    mini_results_dict = {
        "cons_img_idx": cons_img_idx,
        "cons_item_id": cons_item_id.item(),
        "num_shop_imgs": shop_item_id_counts.item(),
        "closest_shop_img_idxs": closest_shop_img_idxs.tolist(),
        "closest_shop_item_ids": closest_shop_item_ids.tolist(),
        "closest_shop_img_dists": closest_shop_img_dists.tolist()
    }

    if train_desired_cons_img_zzidx == 0:
        pprint.pprint(mini_results_dict)
        print()

    eval_data["results"]["train"].append({
        "cons_img_idx": cons_img_idx,
        "cons_item_id": cons_item_id.item(),
        "num_shop_imgs": shop_item_id_counts.item(),
        "closest_shop_img_idxs": closest_shop_img_idxs.tolist(),
        "closest_shop_item_ids": closest_shop_item_ids.tolist(),
        "closest_shop_img_dists": closest_shop_img_dists.tolist()
    })

logger.print("  Current memory usage:")
logger.print(utils.mem.sprint_memory_usage([eval_params["settings"]["device_idx"]], num_spaces=4))

logger.print("Train split examples end")

{'closest_shop_img_dists': [4.678122997357658,
                            4.732720983902535,
                            4.875929480162584,
                            4.893084303981963,
                            4.905858250430601,
                            4.910721254792581,
                            4.922969856840008,
                            4.945568398770011,
                            4.969878786690387,
                            4.979967361025649],
 'closest_shop_img_idxs': [2133,
                           1216,
                           106622,
                           186259,
                           124060,
                           156906,
                           1360,
                           98885,
                           93252,
                           3491],
 'closest_shop_item_ids': [9151,
                           24290,
                           11877,
                           7704,
                           10576,
                    

In [78]:
pprint.pprint(eval_data["results"]["train"][0])

{'closest_shop_img_dists': [4.678122997357658,
                            4.732720983902535,
                            4.875929480162584,
                            4.893084303981963,
                            4.905858250430601,
                            4.910721254792581,
                            4.922969856840008,
                            4.945568398770011,
                            4.969878786690387,
                            4.979967361025649],
 'closest_shop_img_idxs': [2133,
                           1216,
                           106622,
                           186259,
                           124060,
                           156906,
                           1360,
                           98885,
                           93252,
                           3491],
 'closest_shop_item_ids': [9151,
                           24290,
                           11877,
                           7704,
                           10576,
                    